$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Read-Source($relativePath) {
    Get-Content -Raw -Path (Join-Path $root $relativePath)
}

function Assert-Contains($name, $text, $pattern) {
    if ($text -notmatch [regex]::Escape($pattern)) {
        throw "Missing invariant: $name ($pattern)"
    }
}

function Assert-Regex($name, $text, $pattern) {
    if ($text -notmatch $pattern) {
        throw "Missing invariant: $name ($pattern)"
    }
}

function Assert-NotRegex($name, $text, $pattern) {
    if ($text -match $pattern) {
        throw "Unexpected direct path: $name ($pattern)"
    }
}

$botTick = Read-Source "deobfuscated_source/com/rs2/bot/duel/DuelArenaBotTickTask.java"
$botTask = Read-Source "deobfuscated_source/com/rs2/bot/tasks/DuelArenaBotTask.java"
$botDefinition = Read-Source "deobfuscated_source/com/rs2/bot/BotTaskDefinition.java"
$botStart = Read-Source "deobfuscated_source/com/rs2/bot/BotDuelArenaStartTask.java"
$botPlayer = Read-Source "deobfuscated_source/com/rs2/bot/BotPlayer.java"
$configFile = Read-Source "deobfuscated_source/com/rs2/ConfigFile.java"
$serverSettings = Read-Source "deobfuscated_source/com/rs2/ServerSettings.java"
$player = Read-Source "deobfuscated_source/com/rs2/model/player/Player.java"
$gameplayHelper = Read-Source "deobfuscated_source/com/rs2/model/GameplayHelper.java"
$packetHandler = Read-Source "deobfuscated_source/com/rs2/net/packet/handler/PlayerInteractionPacketHandler.java"
$duelRequestTask = Read-Source "deobfuscated_source/com/rs2/net/packet/handler/DuelRequestTask.java"
$duelController = Read-Source "deobfuscated_source/com/rs2/model/gameplay/duel/DuelController.java"
$duelSession = Read-Source "deobfuscated_source/com/rs2/model/gameplay/duel/DuelSession.java"
$duelHistory = Read-Source "deobfuscated_source/com/rs2/model/gameplay/duel/DuelHistory.java"
$duelVictoryTask = Read-Source "deobfuscated_source/com/rs2/model/gameplay/duel/DuelVictoryTask.java"
$duelLocation = Read-Source "deobfuscated_source/com/rs2/model/gameplay/duel/DuelArenaLocationManager.java"
$server = Read-Source "deobfuscated_source/com/rs2/Server.java"
$combatManager = Read-Source "deobfuscated_source/com/rs2/model/combat/CombatManager.java"
$botPvpCombat = Read-Source "deobfuscated_source/com/rs2/bot/combat/BotPvpCombatHandler.java"
$botCombatEscape = Read-Source "deobfuscated_source/com/rs2/bot/combat/BotCombatEscapeHandler.java"
$botCombatHelper = Read-Source "deobfuscated_source/com/rs2/bot/combat/BotCombatHelper.java"
$botPvpSelfTick = Read-Source "deobfuscated_source/com/rs2/bot/combat/BotPvpSelfTargetCombatTickTask.java"
$botPvpOpponentTick = Read-Source "deobfuscated_source/com/rs2/bot/combat/BotPvpOpponentTargetCombatTickTask.java"
$liveConfig = Read-Source "Config.cfg"

Assert-Contains "bot uses normal stake add path" $botTick "getDuelSession().addStakeItem(new ItemStack(DuelArenaBotTask.STAKE_ITEM_ID"
Assert-Contains "setup accept button path" $botTick "handleButtonClick(6674)"
Assert-Contains "confirm accept button path" $botTick "handleButtonClick(6520)"
Assert-Contains "bot uses deferred duel request" $botTick "PlayerInteractionPacketHandler.dispatchDeferredDuelRequest"
Assert-Contains "deferred duel schedules DuelRequestTask" $packetHandler "new DuelRequestTask(null, 1, player2, player, n)"
Assert-Contains "duel request task rechecks validity before completion" $duelRequestTask "canCompleteDuelRequest()"
Assert-Contains "duel request task aborts busy target before setup" $duelRequestTask "this.targetPlayer.getOpenInterfaceId() > 0"
Assert-Contains "duel request task aborts existing duel opponent" $duelRequestTask "this.targetPlayer.getDuelSession().getOpponent() != null"
Assert-Regex "direct lobby challenge bypasses disabled gate" $packetHandler "if \(player\.isInDuelArenaLobby\(\)\)[\s\S]*new DuelRequestTask\(this, 1, targetPlayer, player, actionSequence\)[\s\S]*if \(ServerSettings\.duelingDisabled\)"
Assert-Regex "deferred lobby challenge bypasses disabled gate" $packetHandler "if \(player\.isInDuelArenaLobby\(\)\)[\s\S]*new DuelRequestTask\(null, 1, player2, player, n\)[\s\S]*if \(ServerSettings\.duelingDisabled\)"
Assert-Contains "setup accept checks inventory space" $duelController "hasInventorySpaceForDuel()"
Assert-Contains "stake add removes exact inventory slot" $duelSession "removeItemFromSlot(itemStack, n)"
Assert-Contains "victory returns own stake through reset" $duelSession "player.getDuelController().resetDuel(true)"
Assert-Contains "victory reward uses existing add/drop" $duelVictoryTask "addOrDropItem((ItemStack)object)"
Assert-Contains "disconnect started duel awards opponent" $server "DuelSession.finishDuelVictory(disconnectingPlayer.getDuelSession().getOpponent(), disconnectingPlayer)"
Assert-Contains "disconnect setup duel returns stakes" $server "disconnectingPlayer.getDuelController().resetDuel(true)"
Assert-Contains "death resolves duel loss" $combatManager "getDuelSession().finishDuelLoss(false)"
Assert-Regex "bot rejects unsupported no-melee/no-movement rules" $botTick "NO_MELEE.*NO_MOVEMENT"
Assert-NotRegex "bot does not reject optional no-food rule" $botTick "NO_MELEE\.isEnabledFor\(this\.bot\)[^\r\n]*NO_FOOD"
Assert-NotRegex "bot does not suggest no-food rule" $botTick "MELEE_STAKE_RULES[^\r\n]*NO_FOOD"
Assert-NotRegex "bot adverts do not suggest no-food rule" $botTick "no[- ]?food|NO_FOOD"
Assert-Regex "bot requires selected melee stake rules" $botTick "NO_RANGED.*NO_MAGIC.*NO_SPECIAL_ATTACK.*NO_PRAYER"
Assert-NotRegex "bot tick must not directly award inventory items" $botTick "getInventoryManager\(\)\.add(?:OrDrop)?Item"
Assert-Contains "task seeds real inventory stake coins" $botTask "player.getInventoryManager().addItem(new ItemStack(STAKE_ITEM_ID"
Assert-Contains "task scatters stacked lobby start to preferred area" $botTask "player.moveTo(DuelArenaBotTask.getPreferredLobbyPosition(player))"
Assert-Contains "task uses duel lobby randomizer" $botTask "DuelArenaLocationManager.randomExitPosition()"
Assert-Contains "duel lobby has stable anchor positions" $duelLocation "duelLobbyAnchorPositions"
Assert-Contains "duel lobby exposes bot anchor selector" $duelLocation "lobbyAnchorPosition(Player player)"
Assert-Contains "duel lobby samples around anchor" $duelLocation "randomLobbyPositionNear(Position position, int radius)"
Assert-Contains "duel lobby clamps local samples into lobby" $duelLocation "DuelArenaLocationManager.clamp"
Assert-Contains "duel lobby verifies sampled tile is open" $duelLocation "isOpenLobbyPosition(candidate)"
Assert-Contains "duel task exposes preferred lobby position" $botTask "getPreferredLobbyPosition(Player player)"
Assert-Contains "duel task exposes stable lobby anchor" $botTask "getLobbyAnchorPosition(Player player)"
Assert-Contains "duel task only available to dedicated mode" $botTask "return player.botMode == 7"
Assert-NotRegex "duel task excluded from progressive pool" $botDefinition "progressiveTaskDefinitions[^\r\n]*duelArenaCombatTask"
Assert-Contains "duel manager uses separate task slot" $botTask "player.botDuelArenaTask = new DuelArenaBotTickTask"
Assert-Contains "player stores duel arena manager task" $player "public TickTask botDuelArenaTask"
Assert-Contains "bot reset stops duel arena manager" $gameplayHelper "player.botDuelArenaTask.stop()"
Assert-Contains "generic stuck recovery skips duel bots" $player "shouldSkipGenericBotRecoveryForDuel()"
Assert-Contains "saved non-duel bot clears duel task" $player "Clearing non-duel bot from duel arena task"
Assert-Regex "route teleport recovery skips duel bots" $player "if \(n > 50\) \{\s*if \(this\.shouldSkipGenericBotRecoveryForDuel\(\)\)"
Assert-Contains "winner bot closes reward interface before returning" $botTick "this.bot.packetSender.closeInterfaces()"
Assert-Contains "stake value comparison uses long" $botTick "long opponentStakeValue = this.getStakeValue(opponent)"
Assert-Contains "task has deterministic bot personality roll" $botTask "getPersonalityRoll(Player player, int range)"
Assert-Contains "bot personality changes stake acceptance" $botTick "getMinimumOpponentStakeValuePercent()"
Assert-Contains "duel task defines strength pure build" $botTask "BUILD_STRENGTH_PURE"
Assert-Contains "duel task defines defence tank build" $botTask "BUILD_DEFENCE_TANK"
Assert-Contains "duel task defines low level pure build" $botTask "BUILD_LOW_LEVEL_PURE"
Assert-Contains "duel task exposes risk profile" $botTask "getRiskProfile(Player player)"
Assert-Contains "duel task exposes stake tier" $botTask "getStakeTier(Player player)"
Assert-Contains "duel task varies stake bankroll reserves" $botTask "getStakeReserveMultiplier(Player player)"
Assert-Contains "duel task exposes configurable combat level band" $botTask "BASE_MATCH_LEVEL_BAND"
Assert-Contains "duel task gates combat level matchups" $botTask "isCombatLevelMatchAcceptable(Player bot, Player opponent)"
Assert-Contains "duel task allows selective underdog fights" $botTask "willTakeUnderdogFight(Player player, int levelDifference)"
Assert-Contains "duel bot requester checks matchup quality" $botTick "this.isOpponentMatchupAcceptable(candidate)"
Assert-Contains "duel bot proactive target checks matchup quality" $botTick "this.isOpponentMatchupAcceptable(player)"
Assert-Contains "duel bot setup declines bad matchup" $botTick "getMatchupDeclineMessage(opponent)"
Assert-Contains "duel bot stake acceptance uses stake tier" $botTick "DuelArenaBotTask.getStakeTier(this.bot)"
Assert-Contains "duel bot stake acceptance uses risk profile" $botTick "DuelArenaBotTask.getRiskProfile(this.bot)"
Assert-Contains "duel history records matchup winners" $duelHistory "recentWinnerKeys"
Assert-Contains "duel history counts repeat losses" $duelHistory "countRecentLossesTo(Player loser, Player winner)"
Assert-Contains "duel history lets bots avoid repeat farming" $duelHistory "shouldAvoidRepeatFarm(Player bot, Player opponent)"
Assert-Contains "server settings exposes duel bot enable flag" $serverSettings "public static boolean duelBotsEnabled"
Assert-Contains "server settings exposes duel bot count" $serverSettings "public static int duelBotCount"
Assert-Contains "config accepts duel bot count" $configFile 'new ConfigFile("DUEL_BOTS", 2)'
Assert-Contains "config applies duel bot enable" $configFile "ServerSettings.duelBotsEnabled"
Assert-Contains "live config enables duel bots" $liveConfig "[DUEL_BOTS];1;20"
Assert-Contains "server counts duel bots" $server "configuredBotCount += ServerSettings.duelBotCount"
Assert-Contains "server selects duel bot mode" $server "return 7;"
Assert-Contains "bot player starts duel arena mode" $botPlayer "startDuelArenaBot"
Assert-Contains "sbot command dispatches duel mode" $player "this.botMode == 7"
Assert-Contains "duel start assigns duel task directly" $botStart "BotTaskDefinition.getDuelArenaCombatTask()"
Assert-Contains "duel start records task type" $botStart "this.bot.currentBotTaskTypeId = botTaskDefinition.getTaskTypeId()"
Assert-Contains "duel start records task index" $botStart "this.bot.currentBotTaskIndex = botTaskDefinition.getTaskIndexForType"
Assert-Regex "duel manager stops only on invalid bot ownership" $botTick "this\.bot == null \|\| !this\.bot\.isRegistered\(\) \|\| this\.bot\.currentBotTask != this\.taskDefinition"
Assert-Regex "duel manager survives temporary death cleanup" $botTick "if \(this\.bot\.isDead\(\)\) \{\s*return;\s*\}"
Assert-NotRegex "duel manager must not stop while bot is temporarily dead" $botTick "this\.bot == null \|\| this\.bot\.isDead\(\)"
Assert-Contains "duel bots restock in arena" $botTick "this.taskDefinition.prepareTaskInventory(this.bot)"
Assert-Contains "duel bots restock to preferred lobby position" $botTick "this.bot.moveTo(DuelArenaBotTask.getPreferredLobbyPosition(this.bot))"
Assert-Contains "duel bot food id is shared with tick restock" $botTask "public static final int FOOD_ITEM_ID"
Assert-Contains "duel bots restock low food before next match" $botTick "DuelArenaBotTask.FOOD_ITEM_ID) < RESTOCK_FOOD_THRESHOLD"
Assert-Contains "duel bots use lobby movement cooldown" $botTick "lobbyMoveCooldownTicks"
Assert-Contains "duel bots manage lobby spacing" $botTick "manageLobbySpacing()"
Assert-Contains "duel bots count nearby idle duel bots" $botTick "countNearbyIdleDuelBots"
Assert-Contains "duel bots walk locally with pathfinder" $botTick "PathFinder.findPath(this.bot"
Assert-Contains "duel bots walk instead of run while idling" $botTick "this.bot.getMovementQueue().setRunning(false)"
Assert-Contains "duel bots use challenge scan cooldown" $botTick "challengeScanCooldownTicks"
Assert-Contains "duel bots limit proactive challenge distance" $botTick "PROACTIVE_CHALLENGE_DISTANCE"
Assert-Contains "duel bots wait while outgoing duel request is pending" $botTick "this.bot.getDuelRequestTarget() != null"
Assert-Contains "duel bots expire stale outgoing duel requests" $botTick "expireStaleOutgoingDuelRequest()"
Assert-Contains "duel bots preflight request target availability" $botTick "canSendDuelRequestTo(Player target)"
Assert-Contains "duel bots avoid targets with unrelated pending requests" $botTick "targetRequestTarget != null && targetRequestTarget != this.bot"
Assert-Contains "duel bots build dynamic stake adverts" $botTick "buildAdvertisement()"
Assert-Contains "duel bots format advert stake amount" $botTick "getFormattedStakeAmount()"
Assert-Contains "duel bots have old style rule adverts" $botTick "RULE_ADVERTISEMENTS"
Assert-Contains "duel bots have old style lobby adverts" $botTick "LOBBY_ADVERTISEMENTS"
Assert-NotRegex "duel bot adverts do not self-label builds" $botTick "PURE_ADVERTISEMENTS|TANK_ADVERTISEMENTS|MAIN_ADVERTISEMENTS"
Assert-Contains "duel bots choose randomized bot challenge candidates" $botTick "botCandidates.get(GameUtil.randomInt(botCandidates.size()))"
Assert-Contains "duel bots choose randomized player challenge candidates" $botTick "playerCandidates.get(GameUtil.randomInt(playerCandidates.size()))"
Assert-Contains "duel bots skip busy moving bot challenge targets" $botTick "player.isMoving() || player.getInteractionTarget() != null || player.getDuelRequestTarget() != null"
Assert-Contains "duel bots recover bank-walk task state" $botTick "recoverDedicatedDuelTaskState()"
Assert-Contains "duel bots force dedicated state back to task" $botTick 'this.bot.botTaskState = "do task"'
Assert-Contains "idle duel bots reset stale combat state" $botTick "resetIdleDuelCombatState()"
Assert-Contains "duel combat start refreshes bot combat driver" $botTick "prepareDuelCombatDriver(this.bot, opponent)"
Assert-Contains "duel combat start refreshes bot opponent driver" $botTick "prepareDuelCombatDriver(opponent, this.bot)"
Assert-Contains "duel inventory reset clears runtime combat state" $botTask "resetDuelCombatRuntimeState(player)"
Assert-Contains "player tracks bot pvp tick target" $player "public Player botCombatTickTarget"
Assert-Contains "bot task reset clears combat tick target" $gameplayHelper "player.botCombatTickTarget = null"
Assert-Contains "bot combat helper clears combat tick target" $botCombatHelper "player.botCombatTickTarget = null"
Assert-Contains "pvp tick scheduler replaces stale target tasks" $botPvpCombat "activeCombatTick && player.botCombatTickTarget != target"
Assert-Contains "pvp tick scheduler tags target" $botPvpCombat "player.botCombatTickTarget = target"
Assert-Contains "duel pvp clears escape state" $botPvpCombat "clearDuelArenaEscapeState(player)"
Assert-Contains "duel pvp low food keeps fighting" $botPvpCombat "BotPvpCombatHandler.isDuelArenaBot(player))"
Assert-Regex "high level escape excludes duel bots" $botPvpCombat "escapeHighLevelAttackersEnabled && !BotPvpCombatHandler\.isDuelArenaBot\(player\)"
Assert-Contains "escape handler refuses duel bots" $botCombatEscape "player.currentBotTask instanceof DuelArenaBotTask"
Assert-Regex "self pvp tick returns after target stop" $botPvpSelfTick "this\.stop\(\);\s*return;"
Assert-Regex "opponent pvp tick returns after target stop" $botPvpOpponentTick "this\.stop\(\);\s*return;"
Assert-NotRegex "duel bot tick should not fall through to random next task" $botTick "startNextBotTask"

[pscustomobject]@{
    Probe = "duel-arena-bot-safety"
    Status = "passed"
    Checked = 117
}
